CREATE EXTENSION IF NOT EXISTS vector;
CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS conversations (id uuid PRIMARY KEY, user_id uuid REFERENCES users(id), summary text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS messages (id uuid PRIMARY KEY, conversation_id uuid REFERENCES conversations(id), role text NOT NULL, content text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS memories (id uuid PRIMARY KEY, user_id uuid REFERENCES users(id), kind text NOT NULL, content text NOT NULL, importance smallint NOT NULL, authorized boolean NOT NULL DEFAULT false, embedding vector(1536), created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS memories_embedding_idx ON memories USING hnsw (embedding vector_cosine_ops);
CREATE TABLE IF NOT EXISTS projects (id uuid PRIMARY KEY, user_id uuid REFERENCES users(id), name text NOT NULL, description text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS tasks (id uuid PRIMARY KEY, project_id uuid REFERENCES projects(id), title text NOT NULL, status text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS tools (id uuid PRIMARY KEY, name text NOT NULL UNIQUE, description text NOT NULL, risk text NOT NULL, input_schema jsonb NOT NULL DEFAULT '{}', output_schema jsonb NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS tool_permissions (id uuid PRIMARY KEY, user_id uuid REFERENCES users(id), tool_id uuid REFERENCES tools(id), allowed boolean NOT NULL DEFAULT false, confirmation_required boolean NOT NULL DEFAULT true);
CREATE TABLE IF NOT EXISTS embeddings (id uuid PRIMARY KEY, owner_type text NOT NULL, owner_id uuid NOT NULL, model text NOT NULL, value vector(1536) NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS tool_calls (id uuid PRIMARY KEY, tool_name text NOT NULL, risk text NOT NULL, arguments jsonb NOT NULL, result jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS knowledge_sources (id uuid PRIMARY KEY, url text, title text, trust_score real, retrieved_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS knowledge_documents (id uuid PRIMARY KEY, source_id uuid REFERENCES knowledge_sources(id), content_hash text UNIQUE, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS knowledge_chunks (id uuid PRIMARY KEY, document_id uuid REFERENCES knowledge_documents(id), content text NOT NULL, embedding vector(1536));
CREATE TABLE IF NOT EXISTS research_jobs (id uuid PRIMARY KEY, query text NOT NULL, status text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS automation_jobs (id uuid PRIMARY KEY, name text NOT NULL, schedule text NOT NULL, confirmed boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS audit_logs (id uuid PRIMARY KEY, event text NOT NULL, details jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS system_events (id uuid PRIMARY KEY, type text NOT NULL, payload jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS settings (id uuid PRIMARY KEY, user_id uuid REFERENCES users(id), key text NOT NULL, value jsonb NOT NULL, UNIQUE(user_id,key));
