import { FormEvent, useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { Activity, BrainCircuit, Mic, Send, ShieldCheck, Terminal, Wifi } from "lucide-react";
import "./styles.css";
const API = import.meta.env.VITE_API_URL ?? "http://localhost:8000";
type Message = { role: "user" | "assistant"; text: string };
function App() {
 const [messages,setMessages]=useState<Message[]>([{role:"assistant",text:"ULTRON core online. I am ready to reason, research through approved providers, and operate only within your permissions."}]);
 const [input,setInput]=useState(""); const [mode,setMode]=useState("conversation"); const [busy,setBusy]=useState(false); const [status,setStatus]=useState("CONNECTING");
 useEffect(()=>{fetch(`${API}/system/status`).then(r=>r.ok?r.json():Promise.reject()).then(()=>setStatus("NOMINAL")).catch(()=>setStatus("OFFLINE"))},[]);
 async function submit(e:FormEvent){e.preventDefault(); const text=input.trim();if(!text||busy)return; setMessages(p=>[...p,{role:"user",text}]);setInput("");setBusy(true);try{const r=await fetch(`${API}/chat`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:text,mode})});const data=await r.json();setMessages(p=>[...p,{role:"assistant",text:data.response??data.detail??"Communication channel failed."}])}catch{setMessages(p=>[...p,{role:"assistant",text:"I cannot reach the local API. Start the ULTRON backend, then try again."}])}finally{setBusy(false)}}
 return <main><header><div className="brand"><BrainCircuit/><span>ULTRON</span><small>PERSONAL AI OPERATING SYSTEM</small></div><div className={`status ${status.toLowerCase()}`}><span/> SYSTEM {status}</div></header><section className="dashboard"><aside className="panel navigation"><p className="eyebrow">COMMAND MODE</p>{["conversation","command","research","coding","vision","system","automation","focus","silent"].map(item=><button className={mode===item?"selected":""} onClick={()=>setMode(item)} key={item}>{item}</button>)}<div className="emergency"><ShieldCheck size={16}/><span>Safety interlocks active</span></div></aside><section className="center"><div className="core-wrap"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="core"><div className="core-inner"><BrainCircuit size={68}/></div></div></div><div className="wave">{Array.from({length:36},(_,i)=><i key={i} style={{height:`${12+(i*17)%38}px`}}/>)}</div><p className="mode-label">{busy?"PROCESSING REQUEST":"AWAITING INPUT"}</p><div className="conversation panel">{messages.map((m,i)=><article className={m.role} key={i}><label>{m.role==="assistant"?"ULTRON":"OPERATOR"}</label><p>{m.text}</p></article>)}</div><form onSubmit={submit}><button type="button" className="mic" aria-label="Push to talk"><Mic/></button><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Issue a directive..."/><button className="send" aria-label="Send"><Send/></button></form></section><aside className="right"><div className="panel metric"><p className="eyebrow">SYSTEM MATRIX</p><div><Wifi/> Internet <b>configured</b></div><div><Activity/> Events <b>ready</b></div><div><Terminal/> Tools <b>2 allowed</b></div></div><div className="panel"><p className="eyebrow">ACTIVE PROTOCOL</p><h3>{mode.toUpperCase()}</h3><p>Consequential operations require a preview and explicit confirmation.</p></div><div className="panel"><p className="eyebrow">VOICE PIPELINE</p><p>Push-to-talk is ready for a configured STT/TTS provider. The original voice performance profile never clones an actor.</p></div></aside></section></main>}
createRoot(document.getElementById("root")!).render(<App/>);
